### ISSUE TITLE
Extra category creates when you stop typing in categories to combobox

### ISSUE THREAD

**Issue by umanema** [nsynkde/Tilda#3]
Categories are created on any change of the text of categories combobox. There is a check which deletes category if there is no other clip with that category, but somehow it doesn't work with one before last typed in category

**Comment by vavogt** [comment]
This could be fixed by making it so that you have to hit enter to make changes apply. I.e. if you change the duration of a clip it will not immediately apply upon changing the value, but wait for you to press enter. Feels pretty intuitive actually. The downside: Same applies for selecting a new category. Before pressing enter the selected category will not be applied. That, on the other hand, doesn't feel natural at all..

**Comment by vavogt** [comment]
Fixed by making a separate fucntion "CleanCategories" that removes obsolete categories and is called after each change of text in the category field and also after deletion of clips.
