### ISSUE TITLE
setTC in KeyframeEditor doesn't trigger the event for SetTC

### ISSUE THREAD

**Issue by ehenze** [nsynkde/Tilda#31]
So the time changes only locally and isn't distributed over the network

**Comment by jhnnslmk** [comment]
At the keyframe editor's current state I wouldn't consider this a feature to be implemented.
What happens here is that the Previous/Next mechanics for keyframe clips are used to easier jump to keyframes in order to manipulate them, so one doesn't have to tediously set the Playhead to their positions manually.

A planned overhaul of the Keyframe Editing routine (issue #26) will render this feature request unneccessary, as you would just open a Keyframe Clip's editing mode and select Keyframes by clicking on them, without any need to adjust the timecode in order to write to them.

**Comment by ehenze** [comment]
Well the background is, that if several clients are connected, you want to see the keyframe changes on all of them - and you dont get the exact result if the playhead isn’t moved to the keyframe also there ...

**Comment by jhnnslmk** [comment]
I see, I totally misread your briefing.
Still, I argue that this won't be needed anymore. The use case you're describing should be two separated actions.

By doing this as described above you won't have a detached Playhead position on all clients at any time.
1. You start by having a common TC Position on all clients
2. You open a keyframe clip and edit a keyframe
3. You will see the result of the same TC still as it wasn't changed.

Changing the timecode when editing a Keyframe was merely a hack for when there only was a nodebased Editing available, changing the TC mustn't be necessary when editing values.
