### ISSUE TITLE
Clips should not be active after their last frame

### ISSUE THREAD

**Issue by vavogt** [nsynkde/Tilda#56]
When the playhead is sitting on the far end of a clip that clip should not be counted as active any more.

**Comment by ehenze** [comment]
Changed the issue to 'after' because the playhead is in fact on the frame where the next clip begins. This is also a drawing issue of the playhead, which you see as inbetween to frames, but in fact it has a width and should be as wide as a whole frame, if the resolution allows it. then it would also be clear that the previous clip is not on the playhead.

**Comment by vavogt** [comment]
ya, I like the idea of making the playhead as wide as a frame. That will make things more clear.
